USE kamailio;

LOAD DATA LOCAL INFILE 'dispatcher.csv' 
INTO TABLE dispatcher
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 0 LINES;

LOAD DATA LOCAL INFILE 'domain.csv' 
INTO TABLE domain
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 0 LINES;

LOAD DATA LOCAL INFILE 'trusted.csv' 
INTO TABLE trusted
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 0 LINES;

USE asterisk;

LOAD DATA LOCAL INFILE 'sipusers.csv' 
INTO TABLE sipusers
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
IGNORE 0 LINES;
